services:
  - type: web
    name: jto-playground-docx
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FORMAT
        value: docx
      - key: VITE_AI_ENABLED
        value: "false"
    healthCheckPath: /health

  - type: web
    name: jto-playground-pptx
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FORMAT
        value: pptx
      - key: VITE_AI_ENABLED
        value: "false"
    healthCheckPath: /health
