services:
  - type: web
    name: highcharts-export-server
    runtime: docker
    plan: standard
    dockerfilePath: ./services/highcharts-export-server/Dockerfile
    healthCheckPath: /health

  - type: web
    name: jto-playground-docx
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FORMAT
        value: docx
      - key: VITE_AI_ENABLED
        value: "false"
      - key: HIGHCHARTS_SERVER_URL
        value: https://highcharts-export-server-6iyx.onrender.com
    healthCheckPath: /health

  - type: web
    name: jto-playground-pptx
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FORMAT
        value: pptx
      - key: VITE_AI_ENABLED
        value: "false"
      - key: HIGHCHARTS_SERVER_URL
        value: https://highcharts-export-server-6iyx.onrender.com
    healthCheckPath: /health
