/**
 * Delivery of generated bytes to the client.
 *
 * Default is a path under the output root: a .pptx inlined as base64 costs the
 * agent its context window and the transport a multi-megabyte frame, for a
 * payload it almost always just wants to hand to a viewer. Inlining is
 * available, but only when asked for and only under a hard ceiling (#204).
 */

import * as fs from 'fs/promises';

import { ERROR_CODES, failure, type Failure } from './errors.js';
import type { OutputRoot } from './output-root.js';

/**
 * Ceiling for `outputMode: 'base64'`.
 *
 * 4 MiB of binary is ~5.5 MiB of base64 — already past what most clients will
 * put in a model context, and the point beyond which a path is strictly better
 * for everyone.
 */
export const MAX_INLINE_ARTIFACT_BYTES = 4 * 1024 * 1024;

/**
 * Open flags for the artifact write.
 *
 * `resolveOutputPath` already resolved every symlink on the way to this path,
 * but it returned before the write started; `O_NOFOLLOW` makes the kernel — not
 * a prior check — refuse a link planted in that window. It does not exist on
 * Windows, so an `lstat` immediately before the open backs it everywhere,
 * leaving only the lstat→open sliver uncovered — and only there.
 */
const ARTIFACT_WRITE_FLAGS =
  fs.constants.O_WRONLY |
  fs.constants.O_CREAT |
  fs.constants.O_TRUNC |
  (fs.constants.O_NOFOLLOW ?? 0);

export const MIME_TYPES: Record<string, string> = {
  '.docx':
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.pptx':
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.pdf': 'application/pdf',
  '.png': 'image/png',
};

export type ArtifactMode = 'path' | 'base64';

export type Artifact =
  | {
      mode: 'path';
      /** Absolute path, always inside the output root. */
      path: string;
      /** Path relative to the output root, for display. */
      relative: string;
      bytes: number;
      filename: string;
      mimeType: string;
    }
  | {
      mode: 'base64';
      base64: string;
      bytes: number;
      filename: string;
      mimeType: string;
    };

export interface DeliverArtifactOptions {
  /** Name inside the output root; rejected if it escapes (see `output-root.ts`). */
  filename: string;
  mimeType: string;
  /** Defaults to `path`. */
  mode?: ArtifactMode;
  outputRoot: OutputRoot;
  /** Override the inline ceiling; tests and hosts with tighter budgets use it. */
  maxInlineBytes?: number;
}

export type DeliverArtifactResult = { ok: true; artifact: Artifact } | Failure;

/**
 * Turn a generated buffer into the payload a tool reports.
 *
 * Over-limit inlining is a refusal, not a silent downgrade to a path: an agent
 * that asked for bytes and got a path would go looking for a file it cannot
 * read on a host with no shared filesystem, and never learn why.
 */
export async function deliverArtifact(
  buffer: Buffer,
  options: DeliverArtifactOptions
): Promise<DeliverArtifactResult> {
  const {
    filename,
    mimeType,
    mode = 'path',
    outputRoot,
    maxInlineBytes = MAX_INLINE_ARTIFACT_BYTES,
  } = options;
  const bytes = buffer.byteLength;

  if (mode === 'base64') {
    if (bytes > maxInlineBytes) {
      return failure(
        ERROR_CODES.ARTIFACT_TOO_LARGE,
        `Artifact is ${bytes} bytes, over the ${maxInlineBytes}-byte inline limit.`,
        {
          suggestion:
            'Re-run with outputMode "path" to have the file written under the server output root.',
          context: { bytes, maxInlineBytes, filename },
        }
      );
    }
    return {
      ok: true,
      artifact: {
        mode: 'base64',
        base64: buffer.toString('base64'),
        bytes,
        filename,
        mimeType,
      },
    };
  }

  const resolved = await outputRoot.resolveOutputPath(filename);
  if (!resolved.ok) return resolved;

  const plantedLink = () =>
    failure(
      ERROR_CODES.OUTPUT_ROOT_ESCAPE,
      `Output path became a symlink while writing: "${filename}".`,
      {
        suggestion: 'Retry with a different file name.',
        context: { outputRoot: outputRoot.path, filename },
      }
    );

  // The pre-open half of the race guard, and on Windows all of it: O_NOFOLLOW
  // is 0 there, so without this check the open would follow a planted link and
  // truncate whatever it points at.
  const staged = await fs.lstat(resolved.path).catch(() => undefined);
  if (staged?.isSymbolicLink()) return plantedLink();

  let handle: fs.FileHandle;
  try {
    // A configured root may itself be shared. New artifacts still default to
    // owner-only; callers that intentionally publish them can chmod afterwards.
    handle = await fs.open(resolved.path, ARTIFACT_WRITE_FLAGS, 0o600);
  } catch (err) {
    if ((err as NodeJS.ErrnoException)?.code !== 'ELOOP') throw err;
    return plantedLink();
  }
  try {
    await handle.chmod(0o600);
    await handle.writeFile(buffer);
  } finally {
    await handle.close();
  }
  return {
    ok: true,
    artifact: {
      mode: 'path',
      path: resolved.path,
      relative: resolved.relative,
      bytes,
      filename,
      mimeType,
    },
  };
}
