/**
 * The buffer cache used to store bare Buffers, so a cache HIT could only ever
 * report `warnings: null` — the second render of a document with an
 * unresolvable font went silent. The entry is now `{buffer, warnings}`.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import type { GenerationWarning } from '@json-to-office/shared';
import { CacheService } from '../cache';

const WARNINGS: GenerationWarning[] = [
  {
    component: 'fontRegistry',
    message: 'FONT_UNRESOLVED: "Geist" is not registered.',
    severity: 'warning',
    context: { code: 'FONT_UNRESOLVED' },
  },
];

describe('CacheService', () => {
  let cache: CacheService;
  const doc = { name: 'docx', props: {}, children: [] };

  beforeEach(() => {
    cache = new CacheService();
  });

  afterEach(() => {
    cache.destroy();
  });

  it('round-trips buffer and warnings', () => {
    const key = cache.generateCacheKey(doc);
    const buffer = Buffer.from('generated bytes');

    cache.set(key, { buffer, warnings: WARNINGS }, doc);
    const hit = cache.get(key);

    expect(hit).not.toBeNull();
    expect(hit!.buffer.equals(buffer)).toBe(true);
    expect(hit!.warnings).toEqual(WARNINGS);
  });

  it('round-trips a null warnings field', () => {
    const key = cache.generateCacheKey(doc);
    cache.set(key, { buffer: Buffer.from('x'), warnings: null }, doc);

    expect(cache.get(key)!.warnings).toBeNull();
  });

  it('sizes entries by their buffer length, not the wrapper object', () => {
    // lru-cache throws when `sizeCalculation` returns a non-positive number,
    // which `(value) => value.length` silently would after the value type
    // changed from Buffer to an object.
    const buffer = Buffer.alloc(2048);
    cache.set(cache.generateCacheKey(doc), { buffer, warnings: null }, doc);

    const stats = cache.getStats();
    expect(stats.size).toBe(2048);
    expect(stats.itemCount).toBe(1);
  });

  it('stores nothing when bypassCache is set', () => {
    const key = cache.generateCacheKey(doc);
    cache.set(key, { buffer: Buffer.from('x'), warnings: null }, doc, {
      bypassCache: true,
    });

    expect(cache.get(key)).toBeNull();
  });

  it('refuses to store a document with dynamic content', () => {
    const dynamic = {
      name: 'docx',
      props: {},
      children: [{ name: 'paragraph', props: { text: '{{now}}' } }],
    };
    const key = cache.generateCacheKey(dynamic);

    expect(cache.hasDynamicContent(dynamic)).toBe(true);
    cache.set(key, { buffer: Buffer.from('x'), warnings: null }, dynamic);
    expect(cache.get(key)).toBeNull();
  });

  it('counts hits and misses', () => {
    const key = cache.generateCacheKey(doc);
    cache.get(key);
    cache.set(key, { buffer: Buffer.from('x'), warnings: null }, doc);
    cache.get(key);

    const stats = cache.getStats();
    expect(stats.misses).toBe(1);
    expect(stats.hits).toBe(1);
  });
});
