/**
 * Regenerates THIRD-PARTY-NOTICES.md from the production dependency tree.
 *
 * MIT/BSD/ISC require the copyright + permission notice to travel with any
 * "substantial portion" of the code. npm consumers get that automatically
 * (each dependency ships its own LICENSE), but the Docker image and the
 * browser bundle served from json-to-office.com do not — this file covers
 * those. Run `pnpm notices` after changing runtime dependencies.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface Entry {
  name: string;
  versions: string[];
  paths: string[];
  license: string;
  author?: string;
}

/**
 * Upstreams that carry the OOXML rendering itself, called out by name.
 * `from` is the workspace package that declares the dependency, used as the
 * resolution base for optional peers that pnpm does not hoist to the root.
 */
const HIGHLIGHTS: Record<string, { url: string; from?: string }> = {
  docx: { url: 'https://github.com/dolanmiu/docx' },
  '@office-open/core': {
    url: 'https://github.com/DemoMacro/office-open',
    from: 'packages/core-docx',
  },
  '@office-open/docx': {
    url: 'https://github.com/DemoMacro/office-open',
    from: 'packages/core-docx',
  },
  '@office-open/pptx': {
    url: 'https://github.com/DemoMacro/office-open',
    from: 'packages/core-pptx',
  },
  pptxgenjs: { url: 'https://github.com/gitbrent/PptxGenJS' },
};

const LICENSE_FILE = /^(LICENSE|LICENCE|COPYING|NOTICE)(\.\w+)?$/i;

function licenseText(dir: string): string | null {
  try {
    const file = readdirSync(dir).find((f) => LICENSE_FILE.test(f));
    if (!file) return null;
    return readFileSync(join(dir, file), 'utf-8').trim();
  } catch {
    return null;
  }
}

const raw = execFileSync('pnpm', ['licenses', 'list', '--prod', '--json'], {
  encoding: 'utf-8',
  maxBuffer: 64 * 1024 * 1024,
});

const byLicense: Record<string, Entry[]> = JSON.parse(raw);
const all = Object.values(byLicense).flat();

// `pnpm licenses --prod` skips optional peer dependencies, but the renderers
// behind them ship in the Docker image and on json-to-office.com, so resolve
// any missing highlight straight from the store.
for (const [name, { from }] of Object.entries(HIGHLIGHTS)) {
  if (all.some((e) => e.name === name)) continue;
  // Resolved by path rather than `require.resolve`: these packages gate
  // `./package.json` behind their `exports` map.
  const dir = [
    join(from ?? '.', 'node_modules', name),
    join('node_modules', name),
  ].find((candidate) => existsSync(join(candidate, 'package.json')));
  if (!dir) {
    console.warn(`! ${name} not installed — omitted from notices`);
    continue;
  }
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf-8'));
  const entry: Entry = {
    name,
    versions: [pkg.version],
    paths: [dir],
    license: pkg.license ?? 'Unknown',
    author: typeof pkg.author === 'string' ? pkg.author : pkg.author?.name,
  };
  all.push(entry);
  (byLicense[entry.license] ??= []).push(entry);
}

all.sort((a, b) => a.name.localeCompare(b.name));

const lines: string[] = [
  '# Third-party notices',
  '',
  '<!-- Generated by `pnpm notices` — do not edit by hand. -->',
  '',
  'json-to-office is MIT licensed (see [LICENSE](LICENSE)). It builds on the',
  'open-source projects listed below; their license terms are reproduced verbatim.',
  '',
  '## Core rendering engines',
  '',
];

for (const [name, { url }] of Object.entries(HIGHLIGHTS)) {
  const e = all.find((x) => x.name === name);
  if (e)
    lines.push(
      `- **${name}** ${e.versions.join(', ')} — ${e.license} — ${url}`
    );
}

lines.push(
  '',
  'LibreOffice (Mozilla Public License 2.0) is invoked as a separate process in the',
  'Docker image for rendering and PDF export; it is not linked into this software.',
  'Source: https://www.libreoffice.org/about-us/source-code/',
  '',
  '## Summary',
  '',
  '| License | Packages |',
  '| --- | --- |'
);

for (const [license, entries] of Object.entries(byLicense).sort()) {
  lines.push(`| ${license} | ${entries.length} |`);
}

lines.push('', '## Full license texts', '');

for (const e of all) {
  lines.push(
    `### ${e.name} ${e.versions.join(', ')}`,
    '',
    `License: ${e.license}${e.author ? ` · Author: ${e.author}` : ''}`,
    ''
  );
  const text = licenseText(e.paths[0]);
  lines.push(
    text
      ? '```\n' + text + '\n```'
      : '_No license file found in the published package._',
    ''
  );
}

writeFileSync('THIRD-PARTY-NOTICES.md', lines.join('\n') + '\n');
console.log(`Wrote THIRD-PARTY-NOTICES.md (${all.length} packages)`);
