import type { DocxFeature } from '../packages/core-docx/src/ir/features';
import type { PptxFeature } from '../packages/core-pptx/src/ir/features';

const pptx = {
  masters: 'Authored slide masters.',
  placeholders: 'Named master placeholder regions.',
  'rich-text': 'Multiple formatted runs in one text body.',
  'complex-bullet-glyphs': 'Astral or multi-code-point bullet glyphs.',
  text: 'Text bodies and uniform runs.',
  shapes: 'Preset-geometry shapes.',
  images: 'Raster and vector pictures.',
  svg: 'SVG pictures.',
  'image-crop': 'Picture crop and cover.',
  'image-rounding': 'Rounded or circular picture masks.',
  tables: 'Tables, rows and cells.',
  'table-merged-cells': 'Column and row spans.',
  'table-insets': 'Cell padding written on table cells.',
  'table-rounded-corners': 'Rounded table corners.',
  'table-auto-page': 'Flow long tables onto more slides.',
  charts: 'Native charts with embedded workbooks.',
  'chart-bar-style': 'Bar gap and overlap.',
  'chart-pie-style': 'First-slice angle and doughnut hole.',
  'chart-line-style': 'Line smoothing, width and symbols.',
  'chart-radar-style': 'Radar chart style.',
  'chart-data-labels': 'Chart data-label content and position.',
  'chart-data-border': 'Series and data-point outlines.',
  'chart-axis-scale': 'Axis bounds, units and number format.',
  'chart-axis-visibility': 'Axis and axis-line visibility.',
  'chart-axis-style': 'Axis label rotation and grid lines.',
  'chart-text-style': 'Chart title, legend, axis and label fonts.',
  'solid-fills': 'Solid shape fills.',
  'gradient-fills': 'Gradient shape fills.',
  'pattern-fills': 'Pattern shape fills.',
  'image-fills': 'Images used as shape fills.',
  lines: 'Shape outlines and line elements.',
  shadows: 'Shape and text shadows.',
  backgrounds: 'Solid or image slide backgrounds.',
  'speaker-notes': 'Slide speaker notes.',
  'hidden-slides': 'Hidden-slide state.',
  transitions: 'Slide transitions.',
  'external-links': 'External URL hyperlinks.',
  'internal-links': 'Links to another slide.',
  'text-hyperlinks': 'Hyperlinks attached to text.',
  'element-hyperlinks': 'Hyperlinks covering shapes or images.',
  rotation: 'Shape, text-box and table rotation.',
  'image-transform': 'Picture rotation and flips.',
  'flip-horizontal': 'Horizontal element flips.',
  'flip-vertical': 'Vertical element flips.',
  groups: 'Grouped elements sharing a transform.',
  'proofing-language': 'Per-run proofing language.',
  rtl: 'Right-to-left reading order.',
} satisfies Record<PptxFeature, string>;

const docx = {
  paragraphs: 'Paragraphs and text runs.',
  styles: 'Named paragraph and character styles.',
  numbering: 'Numbering definitions and numbered paragraphs.',
  sections: 'Multiple sections and page setup.',
  columns: 'Multi-column sections.',
  'headers-footers': 'Default, first and even headers and footers.',
  tables: 'Tables, rows and cells.',
  'table-merged-cells': 'Column spans and vertical merges.',
  'floating-tables': 'Tables positioned outside text flow.',
  images: 'Inline pictures.',
  'floating-images': 'Anchored pictures with text wrapping.',
  'svg-images': 'SVG pictures with raster fallbacks.',
  'text-frames': 'Floating paragraph frames.',
  'text-boxes': 'Native shape text boxes.',
  'drawing-groups': 'Grouped DrawingML shapes and pictures.',
  charts: 'Native charts with embedded workbooks.',
  toc: 'Table-of-contents fields.',
  'cached-toc': 'Pre-rendered table-of-contents entries.',
  fields: 'Arbitrary Word fields.',
  'cached-fields': 'Cached field results.',
  hyperlinks: 'Document hyperlinks.',
  bookmarks: 'Named document bookmarks.',
  'cross-references': 'Links and fields targeting bookmarks.',
  comments: 'Document comments.',
  'comment-threads': 'Threaded and resolvable comments.',
  footnotes: 'Footnotes.',
  endnotes: 'Endnotes.',
  revisions: 'Inserted and deleted content.',
  breaks: 'Page, column and line breaks.',
  shading: 'Paragraph and table shading.',
  borders: 'Paragraph, table and page borders.',
  'tab-stops': 'Paragraph tab stops.',
  'proofing-language': 'Per-run proofing language and no-proof.',
  'custom-properties': 'Custom document properties.',
  rtl: 'Right-to-left paragraph direction.',
} satisfies Record<DocxFeature, string>;

export const rendererFeatureNotes = { pptx, docx };
