/**
 * The template gallery, bundled with the package.
 *
 * The nine designed documents used to be reachable only over the network, from
 * the playground that serves them — so the cold path, which is the one this
 * programme is about, never saw a designed document at all (#322). They ship
 * here instead: gzipped JSON, a low-DPI contact sheet per template, and a
 * manifest saying what each one is for.
 *
 * Gzipped because they are large and repetitive — 3.4 MB of coordinate
 * compositions compress to 250 KB, which is the difference between a bundle
 * worth shipping and one that is not. Decompression happens on read, so a
 * client that never asks for a template never pays for one.
 *
 * The thumbnails are real renders, generated by `pnpm generate:gallery` and
 * committed. They cannot be produced at install time: rendering needs
 * LibreOffice, poppler and the media directory, none of which an npm install
 * has. `pnpm validate:assets` re-derives the manifest and fails when it has
 * drifted from the documents.
 */

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';

import type { FormatName } from '../lib/adapters.js';

export interface TemplateManifest {
  name: string;
  format: FormatName;
  archetype: string;
  whenToUse: string;
  theme: string;
  /** Pages for a document, slides for a deck. Measured, not estimated. */
  pages: number;
  components: Readonly<Record<string, number>>;
  slots: Readonly<Record<string, number>>;
  externalAssets: readonly string[];
  externalFonts: readonly string[];
  hash: string;
  bytes: { document: number; gzipped: number; thumbnail: number };
}

/**
 * Where the assets are, from wherever this module was loaded.
 *
 * Two layouts have to work: the published package, where this is
 * `dist/index.js` and the assets are one level up, and the repo, where this is
 * `src/templates/gallery.ts` and they are two. Candidates rather than a build
 * step, because a build step that copies assets is one more thing that can be
 * skipped and leave the server serving nothing.
 */
function assetsDir(): string | undefined {
  const here = path.dirname(fileURLToPath(import.meta.url));
  for (const candidate of [
    path.resolve(here, '../assets'),
    path.resolve(here, '../../assets'),
    path.resolve(here, '../../../assets'),
  ]) {
    if (existsSync(path.join(candidate, 'gallery.json'))) return candidate;
  }
  return undefined;
}

let memo:
  | { manifests: TemplateManifest[]; dir: string | undefined }
  | undefined;

function load(): { manifests: TemplateManifest[]; dir: string | undefined } {
  if (memo) return memo;
  const dir = assetsDir();
  if (dir === undefined) {
    memo = { manifests: [], dir: undefined };
    return memo;
  }
  try {
    const parsed = JSON.parse(
      readFileSync(path.join(dir, 'gallery.json'), 'utf8')
    ) as { templates: TemplateManifest[] };
    memo = { manifests: parsed.templates ?? [], dir };
  } catch {
    // A gallery that cannot be read is an absent gallery, not a dead server:
    // every other tool works without it.
    memo = { manifests: [], dir };
  }
  return memo;
}

/** Every bundled template's manifest, in name order. */
export function galleryManifests(format?: FormatName): TemplateManifest[] {
  const { manifests } = load();
  const all = [...manifests].sort((a, b) => a.name.localeCompare(b.name));
  return format ? all.filter((entry) => entry.format === format) : all;
}

export function galleryManifest(name: string): TemplateManifest | undefined {
  return load().manifests.find((entry) => entry.name === name);
}

/** The document itself, decompressed on demand. */
export function galleryDocument(name: string): unknown | undefined {
  const { dir } = load();
  if (dir === undefined || galleryManifest(name) === undefined)
    return undefined;
  try {
    return JSON.parse(
      zlib
        .gunzipSync(readFileSync(path.join(dir, 'templates', `${name}.gz`)))
        .toString('utf8')
    );
  } catch {
    return undefined;
  }
}

/** The contact sheet for a template: every page, low DPI, one PNG. */
export function galleryThumbnail(name: string): Buffer | undefined {
  const { dir } = load();
  if (dir === undefined || galleryManifest(name) === undefined)
    return undefined;
  const file = path.join(
    dir,
    'thumbnails',
    `${name.replace(/\.json$/, '')}.png`
  );
  try {
    return readFileSync(file);
  } catch {
    return undefined;
  }
}

/** Drop the memo. Tests use it to isolate a missing-assets case. */
export function resetGallery(): void {
  memo = undefined;
}
