/**
 * macOS: make staged fonts visible to the soffice child process by
 * registering them *inside* soffice via a Python macro bound to the
 * `OnStartApp` event.
 *
 * Why this works on macOS 26. Apple tightened `CTFontManagerScopeSession`
 * and `kCTFontManagerScopePersistent` to require signed+notarized callers
 * (unsigned Node processes get `paramErr -50`), and `Process` scope only
 * registers fonts for the calling process — so the Node server can't
 * register fonts the soffice child sees. But Process scope DOES work from
 * inside soffice. LibreOffice for macOS bundles Python 3.12 with `ctypes`,
 * and UNO lets us bind a Python macro to application-start events. We seed
 * a per-invocation UserInstallation profile with:
 *
 *   - `user/Scripts/python/JtoFontRegister.py`  — a ~20-line macro that
 *     reads `JTO_FONT_PATHS` from the process env and calls
 *     `CTFontManagerRegisterFontsForURL(url, kScopeProcess, NULL)` via
 *     ctypes for each path (Process = 1 in Core Text's scope enum).
 *   - `user/registrymodifications.xcu` — binds the macro to `OnStartApp`
 *     and sets `MacroSecurityLevel=0` for this ephemeral profile only.
 *
 * SECURITY INVARIANT — macro execution scope. The seeded profile disables
 * soffice's macro-security prompt (`MacroSecurityLevel=0`) so our
 * OnStartApp macro runs without a dialog. This profile MUST ONLY be used
 * to open files this server just generated (i.e., well-formed outputs
 * from `@json-to-office/core-*`). Piping user-supplied .docx/.pptx/.odt
 * through a soffice invocation that uses this stager would execute any
 * embedded VBA/Basic macros silently — an RCE primitive. If a future
 * code path ever converts user-supplied documents (e.g. "PDF-ify my
 * upload"), it must build a separate converter that does NOT share this
 * profile, or call soffice with `--safe-mode` / a default profile.
 *
 * Flow: the converter spawns
 *   `soffice --headless -env:UserInstallation=file://<tempDir>/user-profile ...`
 * with env `{ JTO_FONT_PATHS: "<ttf1>:<ttf2>:..." }`. LO boots, reads our
 * seeded profile, fires `OnStartApp`, runs our macro, registers each
 * staged TTF at Process scope in its own process. Font enumeration then
 * resolves the synthetic family names (`Inter Bold`, `Source Code Pro
 * Medium`, …) against those Process-scope registrations. The PDF export
 * ships the correct glyphs.
 *
 * Elegant side-effects:
 *   - Nothing outside the converter's `tempDir` is touched. The user's
 *     real `~/Library/Fonts` and `~/Library/Application Support/LibreOffice`
 *     stay untouched.
 *   - Cleanup is the converter's `fs.rm(tempDir, …)` — no orphan sweep
 *     needed. If Node crashes mid-conversion, the per-invocation tempDir
 *     is reaped by macOS tmpreaper (or the OS's next boot cleanup).
 *   - No DYLD injection, no notarized helper, no filesystem-scan races.
 *
 * Failure mode: if LibreOffice can't run the macro for any reason
 * (macro-security policy applied at bootstrap before our XCU loads,
 * Python not present in a minimal LO build, …) the soffice process still
 * runs and produces a PDF — just with system-fallback fonts, exactly the
 * pre-fix behavior. Non-catastrophic. Diagnose via stderr: the macro
 * writes failures to stderr via `print(..., file=sys.stderr)`.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { ResolvedFont } from '@json-to-office/shared';
import {
  synthesizeFamilyName,
  rewriteFontFamilyName,
} from '@json-to-office/shared';
import type { FontStager, FontStageHandle } from './types';
import { nextStagingId, safeFilenamePart } from './types';

/**
 * Python macro source. Written verbatim into
 * `<profile>/user/Scripts/python/JtoFontRegister.py`. Kept inline (rather
 * than a separate .py asset) so this TypeScript module is self-contained
 * and survives bundler reshuffles — no runtime file-system lookup for a
 * static asset.
 */
const PYTHON_MACRO = `# Auto-generated by @json-to-office/jto. Runs inside soffice on OnStartApp
# to make staged fonts visible to LibreOffice's font enumeration. macOS 26
# blocks Session/Persistent CT registration for unsigned callers, but
# Process scope still works from inside the target process — which is
# exactly where this macro runs.
import os
import sys
import ctypes
import ctypes.util


def _log(msg):
    # soffice swallows Python stdout in headless mode; stderr surfaces to
    # the parent's pipe. The stager doesn't read this today but the
    # converter logs stderr on failure, which is how we'll debug.
    sys.stderr.write("[jto-font-register] " + msg + "\\n")


def register(*_args):
    paths_env = os.environ.get("JTO_FONT_PATHS", "")
    if not paths_env:
        return
    try:
        cf = ctypes.CDLL(ctypes.util.find_library("CoreFoundation"))
        ct = ctypes.CDLL(ctypes.util.find_library("CoreText"))
    except Exception as e:
        _log("failed to load CoreFoundation/CoreText: " + repr(e))
        return
    cf.CFURLCreateFromFileSystemRepresentation.argtypes = [
        ctypes.c_void_p, ctypes.c_char_p, ctypes.c_long, ctypes.c_bool,
    ]
    cf.CFURLCreateFromFileSystemRepresentation.restype = ctypes.c_void_p
    cf.CFRelease.argtypes = [ctypes.c_void_p]
    ct.CTFontManagerRegisterFontsForURL.argtypes = [
        ctypes.c_void_p, ctypes.c_uint32, ctypes.c_void_p,
    ]
    ct.CTFontManagerRegisterFontsForURL.restype = ctypes.c_bool

    kCTFontManagerScopeProcess = 1
    registered = 0
    for p in paths_env.split(os.pathsep):
        if not p:
            continue
        try:
            b = p.encode("utf-8")
            url = cf.CFURLCreateFromFileSystemRepresentation(
                None, b, len(b), False
            )
            if not url:
                _log("CFURL failed for " + p)
                continue
            ok = ct.CTFontManagerRegisterFontsForURL(
                url, kCTFontManagerScopeProcess, None
            )
            cf.CFRelease(url)
            if ok:
                registered += 1
            else:
                _log("CT register returned false for " + p)
        except Exception as e:
            _log("exception registering " + p + ": " + repr(e))
    _log("registered " + str(registered) + " font(s) at Process scope")


# Expose under "register" (event-binding URL) and module-level run so
# command-line vnd.sun.star.script invocation works either way.
g_exportedScripts = (register,)
`;

/**
 * XCU that LO merges into its Bootstrap registry on startup. Two keys:
 *
 *   1. `/org.openoffice.Office.Events/ApplicationEvents/Bindings/OnStartApp`
 *      → fires our Python macro before any document is loaded, so font
 *      registration completes before LO enumerates fonts for rendering.
 *
 *   2. `/org.openoffice.Office.Common/Security/Scripting/MacroSecurityLevel`
 *      → 0 (allow all). This only applies to the ephemeral UserInstallation
 *      profile we create under `<tempDir>/user-profile`; the user's real
 *      LibreOffice profile config is untouched. Scope of the security
 *      relaxation is bounded by the per-invocation profile's lifetime.
 */
const REGISTRY_MOD_XCU = `<?xml version="1.0" encoding="UTF-8"?>
<oor:items xmlns:oor="http://openoffice.org/2001/registry" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <item oor:path="/org.openoffice.Office.Events/ApplicationEvents/Bindings">
    <node oor:name="OnStartApp" oor:op="replace">
      <prop oor:name="BindingURL" oor:type="xs:string">
        <value>vnd.sun.star.script:JtoFontRegister.py$register?language=Python&amp;location=user</value>
      </prop>
    </node>
  </item>
  <item oor:path="/org.openoffice.Office.Common/Security/Scripting">
    <prop oor:name="MacroSecurityLevel" oor:op="fuse">
      <value>0</value>
    </prop>
  </item>
</oor:items>
`;

export class MacOSCoreTextStager implements FontStager {
  async stage(
    fonts: ResolvedFont[],
    tempDir: string
  ): Promise<FontStageHandle> {
    const embeddable = fonts.filter((r) => r.sources.length > 0);
    if (embeddable.length === 0) {
      return { envOverrides: {}, cleanup: async () => {} };
    }

    // Fonts go to a subdir of the converter's tempDir. No ~/Library writes.
    const fontsDir = path.join(tempDir, 'fonts');
    await fs.mkdir(fontsDir, { recursive: true });

    const id = nextStagingId();
    const fontPaths: string[] = [];
    const staged: {
      family: string;
      weight: number;
      italic: boolean;
      path: string;
    }[] = [];
    let serial = 0;
    for (const r of embeddable) {
      for (const s of r.sources) {
        serial += 1;
        const suffix = s.italic ? 'i' : 'r';
        // Rewrite the TTF's internal family name to match the synthetic
        // sub-family the doc references (e.g. "Inter Light"). Without
        // this, Core Text indexes the staged file as "Inter" and
        // LibreOffice can't resolve `rFonts w:ascii="Inter Light"`.
        const synth = synthesizeFamilyName(r.family, s.weight, s.italic);
        const data =
          synth.family === r.family
            ? s.data
            : rewriteFontFamilyName(s.data, synth.family);
        const name = `${safeFilenamePart(synth.family)}-${s.weight}${suffix}-${id}-${serial}.ttf`;
        const full = path.join(fontsDir, name);
        await fs.writeFile(full, data);
        fontPaths.push(full);
        staged.push({
          family: synth.family,
          weight: s.weight,
          italic: s.italic,
          path: full,
        });
      }
    }

    if (process.env.JTO_DEBUG_FONTS === '1') {
      // eslint-disable-next-line no-console
      console.log(
        '[jto macos-stager] staged ' +
          staged.length +
          ' font(s) for CT Process-scope registration; JTO_FONT_PATHS has ' +
          fontPaths.length +
          ' entries\n' +
          staged
            .map(
              (s) =>
                `  ${s.family} (w=${s.weight}${s.italic ? ' italic' : ''}) → ${path.basename(s.path)}`
            )
            .join('\n')
      );
    }

    // Seed the per-invocation UserInstallation profile. The converter
    // spawns soffice with `-env:UserInstallation=file://<tempDir>/user-profile`,
    // so LO reads the macro + event binding from these exact paths.
    const profileUser = path.join(tempDir, 'user-profile', 'user');
    const scriptsDir = path.join(profileUser, 'Scripts', 'python');
    await fs.mkdir(scriptsDir, { recursive: true });
    await fs.writeFile(
      path.join(scriptsDir, 'JtoFontRegister.py'),
      PYTHON_MACRO
    );
    await fs.writeFile(
      path.join(profileUser, 'registrymodifications.xcu'),
      REGISTRY_MOD_XCU
    );

    return {
      envOverrides: {
        // Colon-separated list of staged TTF paths (`:` matches Python's
        // `os.pathsep` on macOS). The macro reads this at OnStartApp.
        JTO_FONT_PATHS: fontPaths.join(':'),
        // Force LibreOffice's Core Graphics backend. Skia on macOS can
        // skip Core Text's freshly-registered fonts in some builds.
        SAL_DISABLE_SKIA: '1',
      },
      cleanup: async () => {
        // No-op: the converter's `fs.rm(tempDir, { recursive: true })` in
        // its own finally block sweeps everything we wrote here.
      },
    };
  }
}
